@startuml Manage Tournament
title Manage Tournament
Actor Admin #palegreen
participant Website
database Server #brown
hide footbox

alt Manage Teams
    Admin->Website: manageTeamsButton()
    Website-->Admin: redirect(/tournament/id/teams)
    opt Add 
        Admin->Website: addTeam(name,users)
            opt Error
                Website-->Admin: displayError(error)
            end
        Website->Server: addTeam(id,name,users)
        Server-->Website: postTeam(team)
        Website-->Admin: updateTeamList(team)
    end
    opt Edit
        Admin->Website: 
    end
    opt Delete
    end
end

alt Select Match Winner
    Admin->Website: chooseWinner(match,team)
    Website->Server: updateMatch(id:matchID,winner:teamID)
        activate Server
    Server-->Website: updatePartentOf(child:matchID)
        deactivate Server
    Website-->Admin: displayTournament(Tournament)
end

alt Delete Tournament
    Admin->Website: 
end


@enduml