@startuml Guest View
title Guest View
skinparam actorStyle awesome
actor Guest #LightBlue
participant Website
database Server #Brown
hide footbox

Guest->Website: viewTournament(Tournament)
activate Guest
activate Website
Website->Server: fetchTournament(Tournament)
activate Server
Server-->Website: {status: success | failure}
deactivate Server
alt status = success
Website-->Guest: displayTournament(Tournament)
else status = failure 
Website-->Guest: displayError(error)
deactivate Guest
deactivate Website
end

@enduml