@startuml Manger View
title Manager View
skinparam actorStyle awesome

Actor Manager #lime
participant Website
database Server #brown

note left of Manager #white
**Managers can do** 
**everything an admin can,**
**these are additions**
end note

alt View Admins
Manager->Website: viewAdmins()
activate Manager
activate Website
activate Server
    Website->Server: requestList(Admins)
    Website<--Server: sendList(Admins)
deactivate Server
    Manager<--Website: displayAdmins()
deactivate Manager
deactivate Website
end

alt Add Admins
    Manager->Website: createAdmin(email)
    activate Manager
    activate Website
activate Server
    Website->Server: createAdmin(email)
    Website<--Server: {status: success | failure}
deactivate Server
    opt status = success
        Manager<--Website: displayInfo(Success)
    activate Server
        Website->Server: requestList(Admins)
            Website<--Server: sendList(Admins)
    deactivate Server
        Manager<--Website: displayAdmins()
    
    else status = failure
        Manager<--Website: displayError(error)  
    end
deactivate Manager
deactivate Website
end

alt Remove Admins
    Manager->Website: removeAdmin(name)
    activate Manager
    activate Website
activate Server
    Website->Server: removeAdmin(id)
    Website<--Server: {status: success | failure}
deactivate Server
    opt status = success
        Manager<--Website: displayInfo(Success)
    activate Server
        Website->Server: requestList(Admins)
            Website<--Server: sendList(Admins)
    deactivate Server
        Manager<--Website: displayAdmins()
    
    else status = failure
        Manager<--Website: displayError(error)  
    end
deactivate Manager
deactivate Website
end




@enduml