@startuml User View
title User View
actor User #LightBlue
participant Website
database Server #Brown
hide footbox

User->Website: viewTournament(Tournament)
activate User
activate Website
Website->Server: fetchTournament(Tournament)
activate Server
Server-->Website: {status: success | failure}
deactivate Server
alt status = success
Website-->User: displayTournament(Tournament)
else status = failure 
Website-->User: displayError(error)
deactivate User
deactivate Website
end

@enduml

